### ISSUE TITLE
Exception in MessageQueue callback:handleReceiveCallback

### ISSUE THREAD

**Issue by caopengfei** [chrisbanes/PhotoView#236] opened 2015-01-16 03:18 UTC
```
01-16 11:13:43.918: E/InputEventReceiver(6256): Exception dispatching input event.
01-16 11:13:43.918: E/MessageQueue-JNI(6256): Exception in MessageQueue callback: handleReceiveCallback
01-16 11:13:43.938: E/MessageQueue-JNI(6256): java.lang.IllegalArgumentException: pointerIndex out of range
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.MotionEvent.getX(MotionEvent.java:1979)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1769)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2473)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.View.dispatchPointerEvent(View.java:7894)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3986)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3865)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3426)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3476)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3445)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3552)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3453)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3609)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3426)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3476)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3445)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3453)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3426)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5571)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5551)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5522)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5651)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.os.MessageQueue.nativePollOnce(Native Method)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.os.MessageQueue.next(MessageQueue.java:138)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.os.Looper.loop(Looper.java:123)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at android.app.ActivityThread.main(ActivityThread.java:5034)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
01-16 11:13:43.938: E/MessageQueue-JNI(6256): 	at dalvik.system.NativeStart.main(Native Method)
01-16 11:13:43.938: D/AndroidRuntime(6256): Shutting down VM
01-16 11:13:43.938: W/dalvikvm(6256): threadid=1: thread exiting with uncaught exception (group=0x41a65d58)
01-16 11:13:43.998: E/AppCrash(6256): 11:13:44
01-16 11:13:43.998: E/AppCrash(6256): java.lang.IllegalArgumentException: pointerIndex out of range
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.MotionEvent.getX(MotionEvent.java:1979)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.support.v4.view.MotionEventCompatEclair.getX(MotionEventCompatEclair.java:32)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.support.v4.view.MotionEventCompat$EclairMotionEventVersionImpl.getX(MotionEventCompat.java:91)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.support.v4.view.MotionEventCompat.getX(MotionEventCompat.java:219)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:1769)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2216)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
01-16 11:13:43.998: E/AppCrash(6256): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2068)
01-16 11:13:43.998: E/AppCrash(6256): 	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1515)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.app.Activity.dispatchTouchEvent(Activity.java:2473)
01-16 11:13:43.998: E/AppCrash(6256): 	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2016)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.View.dispatchPointerEvent(View.java:7894)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3986)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3865)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3426)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3476)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3445)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3552)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3453)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3609)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3426)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3476)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3445)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3453)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3426)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5571)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5551)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5522)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5651)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.os.MessageQueue.nativePollOnce(Native Method)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.os.MessageQueue.next(MessageQueue.java:138)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.os.Looper.loop(Looper.java:123)
01-16 11:13:43.998: E/AppCrash(6256): 	at android.app.ActivityThread.main(ActivityThread.java:5034)
01-16 11:13:43.998: E/AppCrash(6256): 	at java.lang.reflect.Method.invokeNative(Native Method)
01-16 11:13:43.998: E/AppCrash(6256): 	at java.lang.reflect.Method.invoke(Method.java:515)
01-16 11:13:43.998: E/AppCrash(6256): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:807)
01-16 11:13:43.998: E/AppCrash(6256): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:623)
01-16 11:13:43.998: E/AppCrash(6256): 	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by smarek** [comment] 2015-04-02 11:11
Duplicate of #206

**Closed by smarek** 2015-04-02 11:11 UTC
