### ISSUE TITLE
IllegalArgumentException: pointerIndex out of range

### ISSUE THREAD

**Issue by mdzht** [chrisbanes/PhotoView#245] opened 2015-02-26 09:59 UTC
I've checked, in sample there's not same problem. I've got an IAE when I'm doing it, to minimal size on PhotoView.

**Comment by silin** [comment] 2015-03-12 19:46
I found a way to reproduce the issue very easily in case of using of ViewPager with PhotoView items. You have to:
1) Scale down PhotoView with two fingers touch gesture. Do not release any fingers;
2) Release one of fingers;
3) Scroll left or right -> IllegalStateException (pointerIndex out of range).

As a workaround you can use HackyViewPager from this issue:
https://github.com/chrisbanes/PhotoView/issues/35

**Comment by smarek** [comment] 2015-04-02 11:11
Duplicate of #206

**Closed by smarek** 2015-04-02 11:11 UTC
