### ISSUE TITLE
Strange zoom behaviour on double-tap and scroll

### ISSUE THREAD

**Issue by pablisco** [chrisbanes/PhotoView#526] opened 2017-07-14 16:44 UTC
I was playing around with the double-tap and scroll zoom feature and it seems to have two problems:

1. The min and max scales are ignored
2. The image sometimes goes upside down

This is a gif example of what happens:

![ezgif-2-247de35c18](https://user-images.githubusercontent.com/260697/28221555-af2501c2-68bb-11e7-8243-f2ea2313b68b.gif)

From digging around `PhotoViewAttacher` it seems that on `onScale(float, float float)` inside the internal `onGestureListener` the scale is only verified before the `scaleFactor` is applied. May be worth checking it after too. (I'll try to check out the source and do some tests myself if I find time)

Alternatively, is there any way to disable this gesture?

**Comment by Jawnnypoo** [comment] 2017-07-25 22:15
Does this still happen? It should be fixed in the latest `2.1.3`

**Comment by pablisco** [comment] 2017-07-27 13:31
Ah! I'll have to try. Using 2.1.2 at the moment

**Comment by eygraber** [comment] 2017-08-16 04:40
This is still happening for me in 2.1.3

**Comment by shahbaz-man** [comment] 2017-09-02 23:22
Can confirm happens for me too in 2.1.3

**Comment by talklittle** [comment] 2017-09-19 20:02
Duplicate of #434 which points to Android framework bug https://issuetracker.google.com/issues/37129701

**Comment by Jawnnypoo** [comment] 2017-09-19 20:12
Thanks @talklittle

**Closed** 2017-09-19 20:12 UTC

**Comment by pandulapeter** [comment] 2018-01-16 13:35
Even though it's a platform bug, I think we should be able to disable the gesture instead of shipping a buggy implementation. Is there a way to only use the pinch gesture?
